version: 2
jobs:
  build:
    docker:
      - image: testcafe/testcafe

    steps:
      - checkout

      - run:
          name: npm
          command: "npm install"

      - run:
          name: prepare
          command: "npm run prepare-js"

      - run:
          name: Run tests
          command: "npm run test:e2e:circleci --prefix JSDemos"