version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"

      - run:
          name: npm
          command: "npm install"

      - run:
          name: prepare
          command: "npm run prepare-js"

      - run:
          name: Run tests
          command: "npm run test:e2e:circleci --prefix JSDemos"